### ISSUE TITLE
VC内チャットで死ぬ問題

### ISSUE THREAD

**Issue by Chipsnet** [Chipsnet/damare#47]
```
/damare/node_modules/discord.js/src/client/actions/MessageCreate.js:11
    at Receiver.dataMessage (/damare/node_modules/ws/lib/receiver.js:517:14)
      const existing = channel.messages.cache.get(data.id);
    at Receiver.emit (node:events:520:28)
    at Receiver.receiverOnMessage (/damare/node_modules/ws/lib/websocket.js:970:20)
                                        ^
TypeError: Cannot read properties of undefined (reading 'cache')
    at MessageCreateAction.handle (/damare/node_modules/discord.js/src/client/actions/MessageCreate.js:11:41)
    at Object.module.exports [as MESSAGE_CREATE] (/damare/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocket.emit (node:events:520:28)
    at WebSocket.onMessage (/damare/node_modules/ws/lib/event-target.js:132:16)
    at WebSocketShard.onPacket (/damare/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/damare/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocketManager.handlePacket (/damare/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
```

**Comment by Chipsnet** [comment]
エラーが起きた時点でクライアントが死ぬので結局マイグレしないとだめっぽい
